### PR TITLE
Explicit specializations for FesapiHdfProxy::createAnyArray() are now defined outside the class scope.

### PR DESCRIPTION
**Pull request by Hoosayin**
Hi @philippeVerney!

Since the C++ standard does not allow explicit specialization of member method of a class at class scope, I was getting build errors on CentOS 8 for explicit specializations of **FesapiHdfProxy::createAnyArray()** when complied with GCC. On Windows, the current implementation worked fine since MSVC++ is non-compliant to explicit specialization. 

Here's one of the errors:
`error: explicit specialization in non-namespace scope ‘class etp::FesapiHdfProxy’
`

To resolve these errors, template function definition for **FesapiHdfProxy::createAnyArray()** and its explicit specializations have now been moved out of the class scope and implemented in **FesapiHdfProxy.cpp**. 

Explicit specializations are implemented to pull out type-specific code from template method **FesapiHdfProxy::writeSubArrayNd()**.

Also, assigning **anyArrayType** a value upon determining **valueSize** to avoid redundant **if… else…** statements in **FesapiHdfProxy::writeArrayNd()**.

Regards.

### CODE REVIEW

**Comment by philippeVerney** [comment]
Hi @Hoosayin 

Indeed, my mistake!
I remember to have first seen this mistake in the CI in one of your commit but forgot about it at merging time.
And I saw it again after merging as well.

Thanks for the provdided fix but this PR is still with conflicts for now.
 
Since there is no release yet, I would say the FETPAPI development is still very free. I hope to release about october at least for having a official initial version where the support can be operated in a more industrial way.

**Comment by Hoosayin** [comment]
Hi @philippeVerney!

I completely understand. My Apologies for this inconvenience. To resolve the conflicts, I first synced my fork, and then pushed my commits. I should also have tested it on Linux before creating a Pull Request. Now, the implementation complies to the standard and will work on Windows and Linux.

I have tested it on Windows with C++ and Java Client, and on Linux CentOS 8 with C++ Client. 

Yes, it is a great news to have FETPAPI released in the coming months. I wish you all the best. :) 

Regards.

**Comment by philippeVerney** [comment]
Thanks you!

**Comment by Hoosayin** [comment]
You're welcome. :)

**Pull request merged**
